export * from "./loginData";
export * from "./masterData";
export * from "./webLogs";
export * from "./superAdmin";
export * from "./versions"
export * from "./otpLogs";
export * from "./mobileLogs";
export * from "./activity";
export * from "./department";
export * from "./roles";
export * from "./schemes";
export * from "./userData";
export * from "./sectors";
