export * from "./loginData";
export * from "./masterData";
export * from "./webLogs";
export * from "./superAdmin";
export * from "./versions"
export * from "./otpLogs";
export * from "./mobileLogs";
export * from "./activity";
export * from "./department";
export * from "./roleAccess";
export * from "./schemes";
export * from "./userData";
export * from "./dprsPrivate";
export * from "./dprsCommon";
export * from "./sectors";
export * from "./roles";
export * from "./uploadImgAndVideos";
export * from "./questions";
export * from "./questionsDropdownsTypes";
export * from "./QuestionMapping";
export * from "./watershedData";
export * from "./assignedMasters";
export * from "./wsImagesndVideos";
export * from "./childRoles";
export * from "./assignMastersHistory";
export * from "./watershedDataHistory";
export * from "./category";

