import { Activity } from "../entities/activity";
import { AssignedMasters } from "../entities/assignedMasters";
import { AssignMastersHistory } from "../entities/assignMastersHistory";
import { Category } from "../entities/category";
import { ChildRoles } from "../entities/childRoles";
import { Departments } from "../entities/department";
import { DprsCommonLand } from "../entities/dprsCommon";
import { DprsPrivateLand } from "../entities/dprsPrivate";
import { MasterData } from "../entities/masterData";
import { MobileLogs } from "../entities/mobileLogs";
import { OtpLogs } from "../entities/otpLogs";
import { QuestionMapping } from "../entities/QuestionMapping";
import { Questions } from "../entities/questions";
import { QuestionDropdownTypes } from "../entities/questionsDropdownsTypes";
import { RolesAccess } from "../entities/roleAccess";
import { Roles } from "../entities/roles";
import { Schemes } from "../entities/schemes";
import { Sectors } from "../entities/sectors";
import { UploadImgAndVideo } from "../entities/uploadImgAndVideos";
import { UserData } from "../entities/userData";
import { Versions } from "../entities/versions";
import { WaterShedData } from "../entities/watershedData";
import { WaterShedDataHistory } from "../entities/watershedDataHistory";
import { webLogs } from "../entities/webLogs";
import { WatershedImgAndVideo } from "../entities/wsImagesndVideos";
import { AppDataSource } from "./config";

export const schemesRepo = AppDataSource.getRepository(Schemes);
export const sectorsRepo = AppDataSource.getRepository(Sectors);
export const activityRepo = AppDataSource.getRepository(Activity);
export const rolesRepo = AppDataSource.getRepository(Roles);
export const uploadImgAndVideoRepo = AppDataSource.getRepository(UploadImgAndVideo);
export const dprsPrivateLandRepo = AppDataSource.getRepository(DprsPrivateLand);
export const dprsCommonLandRepo = AppDataSource.getRepository(DprsCommonLand);
export const questionMappingRepo = AppDataSource.getRepository(QuestionMapping);
export const questionDropdownTypesRepo = AppDataSource.getRepository(QuestionDropdownTypes);
export const waterShedDataRepo = AppDataSource.getRepository(WaterShedData);
export const waterShedDataHistoryRepo = AppDataSource.getRepository(WaterShedDataHistory);
export const masterDataRepo = AppDataSource.getRepository(MasterData);
export const watershedImgAndVideoRepo = AppDataSource.getRepository(WatershedImgAndVideo);
export const userDataRepo = AppDataSource.getRepository(UserData);
export const categoryRepo = AppDataSource.getRepository(Category);
export const assignedMastersRepo = AppDataSource.getRepository(AssignedMasters);
export const webLogsRepo = AppDataSource.getRepository(webLogs);
export const mobileLogsRepo = AppDataSource.getRepository(MobileLogs);
export const otpLogsRepo = AppDataSource.getRepository(OtpLogs);
export const roleAccessRepo = AppDataSource.getRepository(RolesAccess);
export const departmentsRepo = AppDataSource.getRepository(Departments);
export const questionsRepo = AppDataSource.getRepository(Questions);
export const childRoleRepo = AppDataSource.getRepository(ChildRoles);
export const assignMastersHistoryRepo = AppDataSource.getRepository(AssignMastersHistory);
export const versionRepo = AppDataSource.getRepository(Versions);